name = toolranks
title = Toolranks
optional_depends = default, farming, mcl_tools, mcl_farming, tech, hades_core, hades_farming, hades_vines
min_minetest_version = 5.10
supported_games = *, minetest_game, mineclonia, exile, hades_revisited
unsupported_games = mineclone2
